### ISSUE TITLE
Ensure plugins work with settings.mk

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1015]
Along with prefix and log from #967 and possibly pkg in case people want to do fully out-of-source builds.

**Comment by tonytheodore** [comment]
Also, the dollar/space checks (#1097) should cover all these manually set paths.

**Comment by starius** [comment]
Out-of-source builds are of interest for building something on top of Debian packages with MXE binary distribution. Example 1: https://github.com/mxe/mxe/issues/962#issuecomment-160294290 Example 2: install `qt` to /usr/lib/mxe and build some Qt based tool in a home dir. Is it a possible scenario? The problem is that such a build has to find headers and libs in /usr/lib/mxe, but install build results to some other directory.

**Comment by tonytheodore** [comment]
Also, general docs (see https://github.com/mxe/mxe/pull/1138#issuecomment-169303377).

**Comment by tonytheodore** [comment]
@starius both examples above should be possible, though I'm not sure how the second would work if installing a lib in home directory then a tool that requires it.

**Comment by starius** [comment]
I also don't know how the second should work. Maybe it is a bad idea to mix two MXE directories.
