### ISSUE TITLE
Use Growl/Zenity/libnotify to send desktop notifications when a build succeeds or fails

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#1084]
It's pretty helpful when the system pops up "error" or "success" when I'm letting MXE build in the background.

Note that envvar sanitizing needs to be modified or circumvented since many of these tools read envvars like `DISPLAY`.

**Comment by starius** [comment]
This can be implemented outside the MXE:

```
$ make foo && notify "success" || notify "error"
```

> Note that envvar sanitizing needs to be modified or circumvented since many of these tools read envvars like DISPLAY.

We sanitize only code written in `src/*.mk` build rules. The pop up should be produced by the code which is not sanitized (main Makefile code). E.g., code of `make download-foo` is not sanitized, otherwise it could not access the network as a result of [nonetwork LD_PRELOAD trick](https://github.com/mxe/mxe/blob/c26f3225fba8ffe9dd54db759d4680a1314d350f/Makefile#L439).

**Comment by tonytheodore** [comment]
I'm ambivalent on this, I've spent the past 6-12 months reducing the general amount of notifications I get - preferring to parse logs at some point after-the-fact. When I am expecting a successful build however, I do want to know the result...
