### ISSUE TITLE
How to receive pkg.mxe.cc key from behind a firewall?

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#1204]
Hi,

I fail to receive key `D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB` from behind a firewall blocking port 11371. Moreover `keys.gnupg.net` [seams](https://travis-ci.org/ooxi/violetland/builds/104264280) [to be](https://travis-ci.org/ooxi/violetland/jobs/104267705) [unreliable](https://travis-ci.org/ooxi/violetland/jobs/104271987).

Would it be possible to use another keyserver which is more reliable and available on port 80? Or maybe embed the hole key on command line?

-- ooxi

**Comment by starius** [comment]
You can download the key from the server: http://pkg.mxe.cc/repos/apt/conf/mxeapt.gpg
Do not wget it in your travis script, because gpg would be useless if you import a key downloaded via http.

> Moreover keys.gnupg.net seams to be unreliable.

I happens sometimes. I just restart a job.

> Would it be possible to use another keyserver which is more reliable and available on port 80?

GPG servers share keys automatically. I think you can use any public GPG server. Tell us if you find a stable one.

> Or maybe embed the hole key on command line?

It is a good idea to embed whole key in your repo as a file and to import it in travis script. I used this approach in my projects, but then I found a way to avoid extra file in every project (using gpg servers). When a key is downloaded from gpg server, it is still secure, as its fingerprint is verified.

**Comment by ooxi** [comment]
Thanks I will look around for a more stable key server!

**Comment by starius** [comment]
keyserver.ubuntu.com seems to be stable. Does it work for you?

**Comment by ooxi** [comment]
In the last couple of builds I did not experience a fault caused by the gnupg keyserver. Nevertheless I followed your advice to use `keyserver.ubuntu.com` in order to provide feedback on the stability :)
