### ISSUE TITLE
How can I uninstall mxe

### ISSUE THREAD

**Issue by userow** [mxe/mxe#1221]
How can I uninstall mxe ?

**Comment by starius** [comment]
Do you want to uninstall whole MXE or individual packages?

**Comment by userow** [comment]
First of all - whole.

I've installed it for testing purposes.

**Comment by TimothyGu** [comment]
How did you install it? Through Debian packages or locally?

If locally, then

```sh
rm -rf mxe
```

**Comment by userow** [comment]
OS X, through make / makefile after installing of required tools through MacPorts.

**Comment by starius** [comment]
> `rm -rf mxe`

It doesn't work because of read-only directory:

```bash
$ rm -rf mxe/
rm: cannot remove ‘mxe/usr/readonly/.gitkeep’: Permission denied
```

To remove it, you can use the following commands:

```bash
$ chmod +w mxe/usr/readonly
$ rm -rf mxe
```

I propose to do keep this directory read-only only while building to prevent such a problem in future. Instead of running `chmod -w mxe/usr/readonly` at creation time, we should run it before each build and run `chmod +w mxe/usr/readonly` after each build.

**Comment by tonytheodore** [comment]
@starius wrote:
> I propose to do keep this directory read-only only while building to prevent such a problem in future. 

Agreed, however that may cause (silent) issues with parallel builds. It should be created in `tmp-<pkg>-<target>` instead.

@userow, you'll also want to revert any changes to `$PATH`.

**Comment by starius** [comment]
There are also problems with git in `usr/` created by `build-pkg`:
```
$ git checkout master 
warning: unable to unlink readonly/.gitkeep: Permission denied
```
