### ISSUE TITLE
error when compiling zlib / x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by abma** [mxe/mxe#1280]
console output:
http://pastebin.com/DUfDqqdz

logfile:

http://pastebin.com/JhHJuTwx

basicly the relevant part is imo:

cd '/mnt/data/backup/tmp/mxe/tmp-zlib-x86_64-unknown-linux-gnu/zlib-1.2.8' && CHOST='x86_64-unknown-linux-gnu' ./configure --prefix='/mnt/data/backup/tmp/mxe/usr/x86_64-unknown-linux-gnu' --static
Using ar
Checking for x86_64-unknown-linux-gnu-gcc...
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.

**Comment by abma** [comment]
using 576f8f85fe1a0cfb2697022572c67c8156efeae1

**Comment by tonytheodore** [comment]
What's the output of `gcc -v`? You may have to also install the `build-essential` package on Ubuntu 16.04.

**Comment by tonytheodore** [comment]
`build-essential` isn't needed, a clean install [works](https://gist.github.com/tonytheodore/a0eea7ef0c35c2be4346c5b9f467c039). Check you have all [the requirements](http://mxe.cc/#requirements-debian).

**Comment by tonytheodore** [comment]
Okay, open a new issue if you see the issue again.

**Comment by FrankHB** [comment]
I find here with some related errors  (missing `-fPIC`) on building zlib.

Eventually I find this is caused by [an update of target triplet](https://unix.stackexchange.com/a/226180). It causes the mismatch between the actual prefix of installed toolchain and an out-of-date `$CHOST` in `/etc/makepkg.conf` in my Arch installation. I guess it is the same reason here.
