### ISSUE TITLE
option to download from backup if file signature fails

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1309]
Maybe even enable it by default and print a warning.

It will make builds more reproducible.

**Comment by tonytheodore** [comment]
The current behaviour is somewhat deliberate - if the primary sources change their signature, we need to inspect the tarball to see if it is a malicious change or a minor packaging revision. The latter should always be accompanied by a version bump but not all projects adhere to that.

**Comment by starius** [comment]
We can inspect if it is a warning, not an error.

With current behaviour, we can be certain about no commit that it will build tomorrow. A package changing a tarball (or providing HTML file instead of a tarball...) breaks whole MXE build.

**Comment by tonytheodore** [comment]
Good points, I wasn't thinking about it with a "reproducible" mindset. The purpose of our mirrors is to reduce breakages (a subset of reproducibility) - as the costs of storage and bandwidth decrease (a safe assumption), we can shift such external dependencies to processes in our control.

It seems a little inverted, but we could treat upstream sites as initial seeds and bandwidth savers - the canonical history of a build being our `git` repo and self-hosted source tarballs. That's a large conceptual departure, but it maintains full transparency and is probably closer to the way people expect MXE to work.

I agree such a change should be enabled by default, just not sure how best to handle a situation like #1319. In that case, each tarball would want to some identifier beyond the upstream versioning. We could do something like append the short SHA to the filename so that the exact tarball can be retrieved for each commit. We treat the mirrors as append-only filesystems (with periodic pruning).

Other options would be some manual incrementing versions or using `git` to find a common ancestor, but those seem like busy-work or overkill.

**Comment by starius** [comment]
I think, the mirror itself should be a large git repo.

>  append the short SHA to the filename so that the exact tarball can be retrieved for each commit.

+1

> with periodic pruning

Is it worth it? Storage is even cheaper than bandwidth.

**Comment by tonytheodore** [comment]
> I think, the mirror itself should be a large git repo.

Interesting, a normal git repo or something like [git-annex](https://git-annex.branchable.com/) or [git-lfs](https://git-lfs.github.com/)?

**Comment by starius** [comment]
> Interesting, a normal git repo or something like git-annex or git-lfs?

Probably normal git repo works as all files are rather small.

```bash
$ du -sh pkg/
2.0G    pkg/
$ du -sh pkg/*|sort -h | tail
35M     pkg/cairo-1.14.6.tar.xz
36M     pkg/db-6.1.26.tar.gz
45M     pkg/qtbase-opensource-src-5.6.0.tar.xz
49M     pkg/ossim-1.8.20-1.tar.gz
61M     pkg/pcl-1.7.2.tar.gz
74M     pkg/boost_1_60_0.tar.bz2
88M     pkg/opencv-2.4.10.zip
95M     pkg/gcc-6.1.0.tar.bz2
137M    pkg/qtwebengine-opensource-src-5.6.0.tar.xz
230M    pkg/qt-everywhere-opensource-src-4.8.7.tar.gz
```

Normal git repo works well in build-pkg for binary artifacts which are much larger.

**Comment by tonytheodore** [comment]
git version in #1628 and filesystem-based in #1974. It's not optional though, I can't really imagine a scenario where you'd want to fail since

https://github.com/mxe/mxe/issues/1309#issuecomment-212496588
> We can inspect if it is a warning, not an error
