### ISSUE TITLE
Comparison of 32 bit and 64 bit targets

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1555]
Following on from https://github.com/mxe/mxe/issues/1524#issuecomment-256218906

**Comment by starius** [comment]
32-bit MXE target has a bit more packages available (407 vs 393 - see the [build matrix](http://mxe.cc/build-matrix.html)).
32-bit exe files can run on both 32-bit and 64-bit versions of the OS.
64-bit process can allocate more than 4 gigs of RAM, but it comes at the cost of longer pointers (64 bits instead of 32 bits), which in turn results in more RAM usage, especially by pointer rich applications such as browsers and compilers.
Normally 32-bit exe files are smaller than 64-bit exe files.
64-bit processes are expected to run faster on 64-bit processor than 32-bit ones, because they are native, but I have never measured this.

**Comment by D3m0nKingx** [comment]
ok thank you for the information. Also possible that different Operating Systems i.e. Windows vs LInux may have slightly different performance between 64 and 32 bit applications. Maybe due to also how they handle disk i/o, cpu and ram operations. 

You may close this topic. Thank you for all your help!
