### ISSUE TITLE
cmake toolchain files force CMAKE_BUILD_TYPE to Release

### ISSUE THREAD

**Issue by Akaricchi** [mxe/mxe#1697]
The toolchain files currently have this line:

`set(CMAKE_BUILD_TYPE Release CACHE STRING "Debug|Release|RelWithDebInfo|MinSizeRel" FORCE)`

What is the reason for that? That makes it impossible to override the setting on the commandline (e.g. `cmake -DCMAKE_BUILD_TYPE=Debug`), and I have to employ hacks in my project's CMakeLists just to get around that. If the intent is to build Release by default, why not wrap that line with something like `if("${CMAKE_BUILD_TYPE}" STREQUAL "")`?

**Comment by tonytheodore** [comment]
Looks like there was an issue with [`pcl` recently](https://github.com/mxe/mxe/pull/1621#issuecomment-270176619) that `FORCE` fixed. The [`File too big` error](https://gist.github.com/anonymous/cc13b4dedefd869908c76736b8876a7e#file-pcl_x86_64-w64-mingw32-static-L1033) is probably an upstream `pcl` issue since we used to set `-DCMAKE_BUILD_TYPE=Release` on the command line.

I'm fairly sure this can be moved to the [wrapper script](https://github.com/mxe/mxe/blob/master/src/cmake/conf/target-cmake.in) so it sets the default and can be easily overriden.

**Comment by starius** [comment]
I'll make this change.

The script will check if `-DCMAKE_BUILD_TYPE` is passed in command line and if it is not passed, pass `-DCMAKE_BUILD_TYPE=Release`.

**Comment by tonytheodore** [comment]
It shouldn't need to check as options specified later in the command take precedence.

**Comment by starius** [comment]
> It shouldn't need to check as options specified later in the command take precedence.

This seems to be an undocumented behavior. I can't find its description in [the official documentation](https://cmake.org/cmake/help/v3.2/manual/cmake.1.html). Also, if we don't check for the option explicitly, we will have to put a comment "options specified later in the command take precedence" not to surprise a reader of this code. When I see code like this, I tend to "fix" it, so the comment is essential to stop such desires :-) On the other hand, self-describing code is better than a comment.

**Comment by tonytheodore** [comment]
Admittedly, I don't recall directly observing or reading about that behaviour - I think I only would have noticed if it didn't behave like that in some obvious way. Explicit is better than implicit.

Fixed with #1717
