### ISSUE TITLE
Bash script to install packages on macOS (and BSDs) securely

### ISSUE THREAD

**Issue by vszakats** [mxe/mxe#1708]
This is not an issue, just an announcement that I wrote a script that is able to install a list of packages, together with their dependencies from the debian APT repository. Necessary signature and checksums are all verified.

https://github.com/vszakats/harbour-core/blob/master/package/mpkg_win_dl_mxe.sh

Example:
```bash
$ mpkg_win_dl_mxe.sh mxe-{i686,x86-64}-w64-mingw32.static-gd
```

Caveats:
- It was created for [Travis CI cross-builds](https://github.com/vszakats/harbour-core/blob/c582897d340d2e22b34114ee3ab0b9d9a4756ae5/.travis.yml#L64-L73) for a specific project, but the logic is largely generic.
- For better or worse, packages are installed into the `~/mxe` directory. Symlinks are retargeted for this location.
- Temporary files are stored in above directory.

Requirements:
- `ar` (BSD-specific), `gpg`, `curl`, `openssl`, `awk`, `sed`, `tar`, `gzip`

**Comment by starius** [comment]
Looks interesting! It makes sense to announce it on [the mailing list](https://lists.nongnu.org/mailman/listinfo/mingw-cross-env-list) (maybe after some improvements, see below). Normally announces go there not to the issues.

* It's a shame we don't sign tar.xz files in the repo! Is it the only reason you use Debian packages instead of [tar.xz archieves](http://pkg.mxe.cc/repos/tar/)? I opened a bug about it: https://github.com/mxe/mxe-apt/issues/5

* Can you add `set -xue` in the beginning of the script? Currently it doesn't stop in case of a failure in one of its commands.

* Can you add the script to https://github.com/mxe/mxe/tree/master/tools to keep it in sync with build-pkg? If something changes in build-pkg, it will be reflected in your script in the same commit.

**Comment by vszakats** [comment]
- Yes, I started out by using `.tar.xz` files, but it felt risky to use them without any option to verify them. Even the download goes in cleartext. Digital signatures would have been quite nice indeed. Possibly also for the control files in `http://pkg.mxe.cc/repos/deb-control/*`, which I was using for pulling the list of dependencies. Anyhow the current `.deb` method seems to work nicely and AFAICT without fundamental issues.
- `set -xue`: Agreed on `-ue`. `-x` would make the output very chatty so I wouldn't add it as default (though it could be enabled based on some envvar f.e.)
- Adding it to `tools`, sure, thanks for offering this! I'm going to create a PR for this.

**Comment by vszakats** [comment]
Closing in favour #1711.

**Comment by starius** [comment]
Please take a look at https://github.com/mxe/mxe-apt/pull/6
Starting from the next release the script can download `*.tar.xz` and `*.deb-control` instead of `*.deb` files. What do you think?

**Comment by vszakats** [comment]
I think it's very useful for everyone who wants to download a single package in a verified way.

In context of the `mxe-get` script, where the goal is to download complete dependency trees, I think the current `Packages`/`.deb`-based solution is more practical due the fewer network requests and less possibility for error cases. It may be useful though in the future for systems that don't have any ways to unpack `.deb` files.

Overall, it's nice to have both of these verification systems in place.
