### ISSUE TITLE
Googletest Support

### ISSUE THREAD

**Issue by nordlow** [mxe/mxe#1741]
Is there a specific reason why googletest is not supported on any configuration?:

http://mxe.cc/build-matrix.html

**Comment by tonytheodore** [comment]
googletest/mock are "download-only" packages - they are unpacked in the source tree of `protobuf`, but otherwise not "built" by MXE.

I'm not familiar with these packages and not sure how they are used. I imagine they provide some kind of runtime test-runner with lib/header support for debugging. The runtime execution is something we explicitly disable - but in an ideal world we could build the runtime components, along with the instrumented libs/headers, and transfer to another host for execution.

**Comment by tonytheodore** [comment]
See the latest http://mxe.cc/build-matrix.html, source-only and meta packages are now greyed out.
