### ISSUE TITLE
How to recompile a modified package from a local folder?

### ISSUE THREAD

**Issue by oomek** [mxe/mxe#1777]
I would be very grateful if you spared a few keyboard clicks and explained step by step how can I recompile a SFML package with added some not yet merged commits and add it to my precompiled MXE environment on Ubuntu.

https://github.com/SFML/SFML/pull/928/commits

I read the tutorial on 
http://mxe.cc/#creating-packages
but It's quite complicated and I'm also not sure it applies to precompiled MXE as well.

Thank you in advance.

**Comment by darealshinji** [comment]
Delete `<PREFIX>/usr/<TARGET>/installed/sfml` and run `make sfml` again.

**Comment by dabonetn** [comment]
Ok, I'm trying to do the exact same thing. Exactly how do I substitute the different version of SFML for the one that is downloaded? I've tried replacing the SFML-2.4.2-sources.zip in the pkg directory with the newer zip from github, but it's redownloaded with the original version when I issue the make command.

Disconnecting the machine from the network refuses to build with a download error.

**Comment by darealshinji** [comment]
@dabonetn You need to edit src/sfml.mk so that the checksum and filename match.

**Comment by oomek** [comment]
This is not what I was asking. I've modified some sfml code and I would like to recompile it in MXE from the folder, not a zip file from the server.

**Comment by oomek** [comment]
@dabonetn have you managed to compile SFML from the local folder by any chance?

**Comment by oomek** [comment]
@darealshinji could you help?

**Comment by darealshinji** [comment]
You could add patches with your changes to the mxe source.

**Comment by donbright** [comment]
you could set up a local webserver, and make a tarball of your modified source with a custom version number, and stick it on the server. then you go into sfml.mk, modify the version, and the url, and run 'make update-checksum sfml' (or whatever the mxe instructions say) and it will download your tarball instead of the official one. 

but if thats too much.... you will have to either hack src/sfml.mk or hack the main Makefile of mxe. it is not really designed to allow you to "Easily create a patch" for a project. you have to dip into the Makefiles and change them to do what you want. 

one time when i was playing  around with it, i basically disabled the checksum functions and disabled deleteing of temporary directories. thats the kind of thing you wind up doing. in your case... you might be able to make it copy a directory instead of trying to download a compressed file and uncompress it.

**Comment by tonytheodore** [comment]
If a package has been updated to use out-of-source build variables (I just did [sfml](https://github.com/mxe/mxe/commit/4b3fc30da9017dcba56488749b91338129efe43d)), then it's possible to do:

```
touch src/sfml.mk && \
make sfml sfml_SOURCE_TREE=/path/to/local/repo
```

this will bypass download, checksum, and patching. This works nicely for cmake or qmake projects since there's no generated configure script.

It probably won't work nicely with a pre-compiled install since there are likely timestamp issues that will cause `make` to think it's out-of-date. I have some WIP that does content-checksums instead of file timestamps that I'll try to merge before the next package build.

**Comment by oomek** [comment]
Thanks, that explains why I didn’t have any luck by just touching the mi file.

**Comment by tonytheodore** [comment]
If a package is on github with a straightforward `GH_CONF` (like sfml now does, see below), you can do:
```
make sfml_GH_CONF=oomek/SFML/branches/unstable update-package-sfml
make sfml_GH_CONF=oomek/SFML/branches/unstable sfml_PATCHES= sfml
```
  - setting `foo_GH_CONF` configures all the update/download variables
  - general form of `GH_CONF` is `<owner>/<repo>/branches/<branch>`
  - setting an empty `foo_PATCHES=` disables any patches in the mxe source - a likely scenario if you've pushed all your changes and/or patches have been accepted upstream.
  - these can/should be set in the `foo.mk` file instead of the `make` invocation.

This probably won't work if there's forward slashes in the branch or tag names - it may not be an easy fix that since we use `/` as a separator. I imagine nobody uses this so I'm free to change the general form;)

**Comment by tonytheodore** [comment]
No worries @donbright, those were fair comments - most of the mxe helpers aren't fully documented, it's too much overhead to learn for casual users. Workflow above can be achieved with:
```sh
# unpack current tarball and creates repo in gits/CGAL-4.11
make init-git-cgal 
# apply current patches so you don't have to worry about conflicts
make import-patch-cgal 
cd gits/CGAL-4.11
# make changes and commit noting if it's mxe-specific

# fetch upstream patch - won't work since cgal has different tarball/repo structures but usually can be done
curl -L 'https://github.com/CGAL/cgal/pull/2461.patch' | git am
git commit --amend # add note about patch source so it can be easily removed next update

cd ../..
make cgal cgal_SOURCE_TREE=gits/CGAL-4.11
# all okay
make export-patch-cgal
make cgal
```
The final patch will contain all changes, if you specifically want a separate patch:
```sh
make init-git-cgal 
# cd gits/CGAL-4.11 and make changes
make export-patch-cgal PATCH_NAME=2-fixes
make cgal
```

**Comment by donbright** [comment]
wow, thanks @tonytheodore ... im a bit confused about what the 'upstream patch' is... but that is very cool that there is a make export-patch-pkg feature,

**Comment by tonytheodore** [comment]
The "upstream patch" is when you find a PR or existing patch that can be applied to the tarball sources. In general, anything other than trivial fixes won't apply smoothly since there are many changes since the release.

This is only really useful if you're intending to submit the patch back to mxe - if you're just working on some fix yourself, it's easier to use a local repo with `foo_SOURCE_TREE`, submit those changes to the upstream project, and wait for the next release to pick it up in mxe core. There's no single patch workflow, it depends on what you're trying to do - ideally we'd have less patches and more frequent updates.

**Comment by donbright** [comment]
got it... thanks.

**Comment by oomek** [comment]
Hi, I'm having problems again building SFML from the local path. It was working before nicely with these lines:
```
touch src/sfml.mk && \
make sfml sfml_SOURCE_TREE=/path/to/local/repo
```

But now with the latest SFML pulled from github to the local drive I'm getting the following errors:
```
oomek@radek-pc:~/mxe$ touch src/sfml.mk                                                                                      oomek@radek-pc:~/mxe$ make MXE_TARGETS='x86_64-w64-mingw32.static' sfml sfml_SOURCE_TREE=/mnt/d/Documents/GitKraken/sfml     [local]       sfml                   /mnt/d/Documents/GitKraken/sfml                                                         [build]       sfml                   x86_64-w64-mingw32.static                                                                                                                                                                                            Failed to build package sfml for target x86_64-w64-mingw32.static!                                                           ------------------------------------------------------------                                                                 /home/oomek/mxe/usr/x86_64-w64-mingw32.static/lib/../lib/libsfml-audio-s.a(SoundSource.cpp.obj):SoundSource.cpp:(.text+0x606): undefined reference to `__imp_alGetSourcei'                                                                                /home/oomek/mxe/usr/x86_64-w64-mingw32.static/lib/../lib/libsfml-audio-s.a(SoundSource.cpp.obj):SoundSource.cpp:(.text+0x622): undefined reference to `__imp_alSourcei'                                                                                   collect2: error: ld returned 1 exit status                                                                                   Makefile:827: recipe for target 'build-only-sfml_x86_64-w64-mingw32.static' failed                                           make[1]: *** [build-only-sfml_x86_64-w64-mingw32.static] Error 1                                                             make[1]: Leaving directory '/home/oomek/mxe'                                                                                 real    0m15.856s                                                                                                            user    0m7.750s                                                                                                             sys     0m9.141s                                                                                                             ------------------------------------------------------------                                                                 [log]      /home/oomek/mxe/log/sfml_x86_64-w64-mingw32.static                                                                                                                                                                                             Makefile:827: recipe for target '/home/oomek/mxe/usr/x86_64-w64-mingw32.static/installed/sfml' failed                        make: *** [/home/oomek/mxe/usr/x86_64-w64-mingw32.static/installed/sfml] Error 1
```

**Comment by oomek** [comment]
Tried in `/opt/mxe` but the error remains

```
local]       sfml                   /home/oomek/sfml
[build]       sfml                   i686-w64-mingw32.static

Failed to build package sfml for target i686-w64-mingw32.static!
------------------------------------------------------------
/opt/mxe/usr/i686-w64-mingw32.static/lib/../lib/libsfml-audio-s.a(SoundSource.cpp.obj):SoundSource.cpp:(.text+0x95e): undefined reference to `_imp__alGetSourcei'
/opt/mxe/usr/i686-w64-mingw32.static/lib/../lib/libsfml-audio-s.a(SoundSource.cpp.obj):SoundSource.cpp:(.text+0x981): undefined reference to `_imp__alSourcei'
collect2: error: ld returned 1 exit status
Makefile:827: recipe for target 'build-only-sfml_i686-w64-mingw32.static' failed
make[1]: *** [build-only-sfml_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory '/opt/mxe'
real    0m23.674s
user    0m40.844s
sys     0m34.641s
------------------------------------------------------------
[log]      /opt/mxe/log/sfml_i686-w64-mingw32.static

Makefile:827: recipe for target '/opt/mxe/usr/i686-w64-mingw32.static/installed/sfml' failed
make: *** [/opt/mxe/usr/i686-w64-mingw32.static/installed/sfml] Error 1
```

**Comment by tonytheodore** [comment]
It looks like something has changed with OpenAL detection - that package was recently updated in mxe and builds fine with the release version of sfml.

**Comment by tonytheodore** [comment]
The sfml patch adds `AL_LIBTYPE_STATIC`, you need to do something similar to fix the `_imp__*` issues.
