### ISSUE TITLE
Intel TBB ?

### ISSUE THREAD

**Issue by vlj** [mxe/mxe#1883]
Hi,

is there any plan to add Intel Thread Building Block package to MXE ? I was surprised to see it's not available since it's a rather widespread dependencies. On the other hand maybe there's some incompatibilities between tbb and mingw ? There isn't a lot of useful answer when querying Google about intel tbb and cross compilation so far.

**Comment by tonytheodore** [comment]
There seem to be mingw packages for it:

https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-intel-tbb
https://aur.archlinux.org/packages/mingw-w64-intel-tbb/

so there's no technical reason - just a matter of time. It appears to be a straightforward `cmake` project so that's a promising start.

**Comment by tonytheodore** [comment]
See #1884, builds on all four targets and tested on i686.

**Comment by starius** [comment]
Fixed in https://github.com/mxe/mxe/pull/1884
