### ISSUE TITLE
Docs: what is the best way to update an installation?

### ISSUE THREAD

**Issue by joede** [mxe/mxe#1970]
I've used `git clone` to get a current release of MXE. The compilation has taken two (working) days.

What is the best why to pull an up-to-date version and build only the changes?

I've tried `git pull` and `make` but this rebuilds all packages.

**Comment by tonytheodore** [comment]
In general, `git pull` and `make` will only rebuild changed packages (and their downstream deps). When a package like `mingw-w64` is updated (as it was a few days ago https://github.com/mxe/mxe/commit/cd56aa162375499228fc2e64b36d0744c21aa11b) it will trigger the rebuild of almost everything since `gcc` itself will need to be rebuilt.

You could restrict the packages you're building with `make foo bar ...` to reduce the total time, but changes to the toolchain or native components are always going to rebuild a lot.

**Comment by joede** [comment]
Thank, so I will try again.
