### ISSUE TITLE
liblqr-1 32 and 64 bits shared downloaded but not build.

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2027]
It's in the tilte. Nothing more. The log file is simply empty about build process : 

[gilles@localhost log]$ cat liblqr-1_x86_64-w64-mingw32.shared 
make[1]: Entering directory '/mnt/data/GIT/5.x/project/bundles/mxe/build.win64'
touch '/mnt/data/GIT/5.x/project/bundles/mxe/build.win64/usr/x86_64-w64-mingw32.shared/installed/liblqr-1'
make[1]: Leaving directory '/mnt/data/GIT/5.x/project/bundles/mxe/build.win64'

real    0m3.891s
user    0m3.802s
sys     0m0.040s

Certainly the rule to compile liblqr-1 version 0.4.2 is broken in shared mode.

Happy new year.

Gilles Caulier

**Comment by tonytheodore** [comment]
From the looks of it, the shared build hasn't been enabled for this package - probably no one has tried to get it working yet since there's no notes about why it doesn't work.

Anything unsupported in the in the [build matrix](http://mxe.cc/build-matrix.html) is basically an open issue - PRs are welcome!
