### ISSUE TITLE
gmp is compile error

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2075]
msys2 compile mxe, gmp is error.

log file,  gmp_x86_64-pc-mingw64:
  checking size of mp_limb_t... 0
  configure: error: Oops, mp_limb_t doesn't seem to work
  make[1]: *** [Makefile:825：build-only-gmp_x86_64-pc-mingw64] error 1

I compile x86_64-w64-mingw32.static type.
Win10X64

**Comment by tonytheodore** [comment]
That's not a lot to go on, but I wouldn't really recommend building MXE on msys2 unless you're doing it as an exercise and are prepared for a lot of work.

Is there a reason you can't use the msys2 package manager? Since you're on Win10, you may have more luck with the [Linux Subsystem](http://mxe.cc/#requirements-wsl).
