### ISSUE TITLE
Reduce size of docker image

### ISSUE THREAD

**Issue by mlocati** [mxe/mxe#2444]
I'm trying to reduce the size of a docker image containing cc (`x86_64-w64-mingw32.static` and `i686-w64-mingw32.static` variants).

Here's my Dockerfile:

```Dockerfile
FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update -q \
    && apt-get upgrade -y \
    && apt-get install -y -q --no-install-recommends \
        autoconf \
        automake \
        autopoint \
        bison \
        bzip2 \
        flex \
        g++ \
        g++-multilib \
        gettext \
        git \
        gperf \
        intltool \
        libc6-dev-i386 \
        libgdk-pixbuf2.0-dev \
        libltdl-dev \
        libssl-dev \
        libtool-bin \
        libxml-parser-perl \
        lzip \
        make \
        openssl \
        p7zip-full \
        patch \
        perl \
        pkg-config \
        python \
        ruby \
        sed \
        unzip \
        wget \
        xz-utils \
    && git clone --depth 1 https://github.com/mxe/mxe.git /opt/mxe \
    && cd /opt/mxe \
    && make -j$(nproc) MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static' cc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/mxe/usr/bin:${PATH}"
```

Is it safe to remove the `.ccache` and `.log` directories (with `rm -rf /opt/mxe/.ccache && rm -rf /opt/mxe/.log`)? Any other stuff that can be removed?

**Comment by tonytheodore** [comment]
You should build mxe without ccache (add `MXE_USE_CCACHE=` to make invocation) instead of deleting the `.ccache` directory. The `log` directory is safe to remove, along with `pkg`.

You could slim down the apt requirements also, things like `libgdk-pixbuf2.0-dev` and `libxml-parser-perl` shouldn't be needed to build the toolchain alone. I'm not sure what the bare minimum is, but adding `DONT_CHECK_REQUIREMENTS=1` to the make invocation will skip any checks so you can narrow it down.

**Comment by mlocati** [comment]
@tonytheodore I [applied your hints](https://github.com/mlocati/powershell-phpmanager/blob/master/src/Dockerfile), and the (compressed) image dropped from more than 700 MB [to 333 MB](https://hub.docker.com/repository/docker/mlocati/powershell-phpmanager-src/tags?page=1)
Thank you!
