### ISSUE TITLE
Can't build qtwebkit (x86_64-w64-mingw32.shared target)

### ISSUE THREAD

**Issue by MarcoBorrini99** [mxe/mxe#2789]
With a fresh mxe cloned repo, I'm trying to build qtwebkit with `make MXE_TARGETS="x86_64-w64-mingw32.shared" qtwebkit`...

1) First, it fails at libxslt stage (https://gist.github.com/MarcoBorrini99/e18690a442dac4785b30cf8c333c3432):

Solved with a quick [libxslt.patch](https://gist.github.com/MarcoBorrini99/47008897b6e1013d2edbb87bde0d8391#file-libxslt-patch)

2) Then webkit fails checking icu packge:
```
-- Checking for module 'icu-uc'
--   Package icu-uc was not found in the pkg-config search path.
Perhaps you should add the directory containing `icu-uc.pc'
to the PKG_CONFIG_PATH environment variable
Package 'icu-uc', required by 'world', not found
ESC[31mCMake Error at Source/cmake/FindICU.cmake:82 (message):
  Could not find ICU
Call Stack (most recent call first):
  Source/cmake/OptionsQt.cmake:491 (find_package)
  Source/cmake/WebKitCommon.cmake:55 (include)
  CMakeLists.txt:139 (include)

ESC[0m
-- Configuring incomplete, errors occurred!
See also "/run/media/marco/9605ee9e-b286-43ae-a9db-e69dd394dc40/Projects/mxe/tmp-qtwebkit-x86_64-w64-mingw32.shared/qtwebkit-opensource-src-5.212.build_/CMakeFiles/CMakeOutput.log".
See also "/run/media/marco/9605ee9e-b286-43ae-a9db-e69dd394dc40/Projects/mxe/tmp-qtwebkit-x86_64-w64-mingw32.shared/qtwebkit-opensource-src-5.212.build_/CMakeFiles/CMakeError.log".
make[1]: *** [Makefile:881: build-only-qtwebkit_x86_64-w64-mingw32.shared] Errore 1
make[1]: uscita dalla directory «/run/media/marco/9605ee9e-b286-43ae-a9db-e69dd394dc40/Projects/mxe»
```

Solved adding icu4c as dependency in src/qtwebkit.mk

3) Then icu4c fails while compiling test-icu4c.c because x86_64-w64-mingw32.shared-peldd is missing.

Solved re-adding pe-util as dependency in src/icu4c.mk

4) Then pe-utils [fails](https://gist.github.com/MarcoBorrini99/90b9847880d9f232432a54fff8ef9299) 

Solved with the help of this [patch](https://gist.github.com/MarcoBorrini99/01d227283d5758c92c9c72640edfcef0)

5) qtwebkit finally compiles :-)

Can someone confirms if I did something wrong?

**Comment by cgilles** [comment]
I can confirm the build failure here.

icu4c do not compile : 

[download]    icu4c-release-66.1.tar.gz
[build]       icu4c                  x86_64-pc-linux-gnu
[done]        icu4c                  x86_64-pc-linux-gnu                                    104380 KiB     2m25.213s
[build]       icu4c                  x86_64-w64-mingw32.shared

Failed to build package icu4c for target x86_64-w64-mingw32.shared!
------------------------------------------------------------
cp $(x86_64-w64-mingw32.shared-peldd --all '/mnt/data/7.x/project/bundles/mxe/build.win64/usr/x86_64-w64-mingw32.shared/bin/test-icu4c.exe') '/mnt/data/7.x/project/bundles/mxe/build.win64/usr/x86_64-w64-mingw32.shared/bin/test-icu4c'
bash: x86_64-w64-mingw32.shared-peldd: command not found
cp: missing destination file operand after '/mnt/data/7.x/project/bundles/mxe/build.win64/usr/x86_64-w64-mingw32.shared/bin/test-icu4c'
Try 'cp --help' for more information.
make[1]: *** [Makefile:881: build-only-icu4c_x86_64-w64-mingw32.shared] Error 1
make[1]: Leaving directory '/mnt/data/7.x/project/bundles/mxe/build.win64'
real    2m20.567s
user    6m28.274s
sys     1m6.471s
------------------------------------------------------------

**Comment by tonytheodore** [comment]
@cgilles try after https://github.com/mxe/mxe/commit/f39bb540bc08aca031d9824e3d5e77e82d184252

**Comment by cgilles** [comment]
I confirm. Updating fix the ICU compilation now. Great:

---------- Updating MXE
From https://github.com/mxe/mxe
   2005c4bb..f39bb540  master     -> origin/master
Updating 2005c4bb..f39bb540
Fast-forward
 .github/workflows/build-docs.yml |   20 +
 .travis.yml                      |   15 -
 docs/build-matrix.html           | 3084 +++++++++++++++++++-------------------
 docs/packages.json               |  178 ++-
 src/icu4c.mk                     |    7 -
 tools/travis-push.sh             |   12 -
 6 files changed, 1666 insertions(+), 1650 deletions(-)
 create mode 100644 .github/workflows/build-docs.yml
 delete mode 100644 .travis.yml
 delete mode 100755 tools/travis-push.sh
[git-log]   f39bb540 icu4c: remove peldd bundle example see https://github.com/mxe/mxe/issues/2789#issuecomment-1072966309
make: Nothing to be done for 'tiff'.
make: Nothing to be done for 'expat'.
make: Nothing to be done for 'zlib'.
make: Nothing to be done for 'bzip2'.
make: Nothing to be done for 'pthreads'.
[build]       icu4c                  x86_64-pc-linux-gnu
[done]        icu4c                  x86_64-pc-linux-gnu                                    104380 KiB     0m22.329s
[build]       icu4c                  x86_64-w64-mingw32.shared
[done]        icu4c                  x86_64-w64-mingw32.shared                              357436 KiB     0m28.714s
[download]    freetype-2.11.1.tar.xz
[build]       freetype-bootstrap     x86_64-w64-mingw32.shared
[done]        freetype-bootstrap     x86_64-w64-mingw32.shared                              27888 KiB      0m20.015s
[download]    fontconfig-2.13.1.tar.bz2
[build]       fontconfig             x86_64-w64-mingw32.shared
[done]        fontconfig             x86_64-w64-mingw32.shared                              17528 KiB      0m35.568s
[download]    freetds-1.3.9.tar.bz2
[build]       freetds                x86_64-w64-mingw32.shared
[done]        freetds                x86_64-w64-mingw32.shared                              56596 KiB      1m51.991s
[download]    lzo-2.10.tar.gz
[build]       lzo                    x86_64-w64-mingw32.shared
[done]        lzo                    x86_64-w64-mingw32.shared                              7108 KiB       0m32.099s
[download]    pixman-0.33.6.tar.gz
[build]       pixman    
...

Now i will check to see if QtWebkit pass fine.

Important : i see that ICU is currently disabled in Qt5 rules, probably because ICU was broken previously. ICU is very important to support strings encoding as here we deal with a database to store photo information (digiKam.org).

https://github.com/mxe/mxe/blob/master/src/qtbase.mk#L25


Best

Gilles Caulier

**Comment by cgilles** [comment]
Same problem with ICU support in Qt6base : https://github.com/mxe/mxe/blob/master/src/qt/qt6/qt6-qtbase.mk#L50

**Comment by tonytheodore** [comment]
Do you only need it for shared builds?

You can always do:
```
make qtbase qtbase_CONFIGURE_OPTS=-icu
```
I'll add the same for qt6

**Comment by tonytheodore** [comment]
See https://github.com/mxe/mxe/commit/1dc7e16e87f4d2713ec4df27ed6ca766705b8793

**Comment by cgilles** [comment]
Ok, i see that icu is now optional. I will try, but for the moment to build qt, harfbuzz is broken:

[download]    cairo-1.16.0.tar.xz
[build]       cairo                  x86_64-w64-mingw32.shared
[done]        cairo                  x86_64-w64-mingw32.shared                              106432 KiB     1m7.258s
[download]    harfbuzz-4.1.0.tar.gz
MXE Warning! Downloading harfbuzz from second URL.
[build]       harfbuzz               x86_64-w64-mingw32.shared

Failed to build package harfbuzz for target x86_64-w64-mingw32.shared!
------------------------------------------------------------
[2/84] Compiling C++ object src/libharfbuzz-0.dll.p/hb-buffer-serialize.cc.obj
[3/84] Compiling C++ object src/libharfbuzz-0.dll.p/hb-aat-map.cc.obj
[4/84] Compiling C++ object src/libharfbuzz-0.dll.p/hb-aat-layout.cc.obj
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:898: build-only-harfbuzz_x86_64-w64-mingw32.shared] Error 1
make[1]: Leaving directory '/home/gilles/Documents/7.x/project/bundles/mxe/build.win64'
real    0m18.828s
user    0m25.709s
sys     0m3.215s
------------------------------------------------------------
[log]      /home/gilles/Documents/7.x/project/bundles/mxe/build.win64/log/harfbuzz_x86_64-w64-mingw32.shared

**Comment by cgilles** [comment]
See my new report https://github.com/mxe/mxe/issues/2808
