### ISSUE TITLE
qt6-qtdeclarative fails to build due to missing dependency on tiff somewhere

### ISSUE THREAD

**Issue by mbunkus** [mxe/mxe#2806]
This is a continuation of #2803, which doesn't actually fix the build issue, or rather there's a separate underlying issue.

When I do a fresh checkout of revision 1a4a6b077c796018573f985c95ae1f8a0f8f5842 with a clean `usr` directory and try to build with `make MXE_TARGETS=x86_64-w64-mingw32.static qt6-qtdeclarative`, the `libtiff-4` package isn't found by `$(TARGET)-pkg-config`. Here's the [build log](https://gist.github.com/mbunkus/518f0fd0ec65d78a535124b832be6dd6). See lines 248 & following where the `gsed` call happens.

The problem seems to be that nothing actually depends on `tiff` in the dependency chain for `qt6-qtdeclarative`. Looking at the whole `make` output `tiff` isn't mentioned at all.

Note that the build log's actual failure is linker failure due to `bz2` (errors near the end of the file, lines 1941 & following), but that's just a subsequent fault of the `$(TARGET)-pkg-config` call failing earlier. Also note that the linker error does _not_ complain about `tiff` symbols missing.

I have absolutely zero ideas why linking seems to require symbols from `tiff` when `tiff` isn't even installed, though…

`tiff` is a dependency of `qt6-qtimageformats`, but that one isn't actually a dependency of `qt6-qtdeclarative` (unlike Qt 5 where `qtdeclarative` depends on `qtimageformats` which depends on `tiff`).

**Comment by mabrand** [comment]
I haven't spent a lot of time on this, but my understanding is that qt6-qtdeclarative will detect tiff if it's already built and configure  qml.exe such that it depends on tiff. The problem is that the static dependencies of tiff itself are left out of the link command. Something similar seems to happen with freetype.

Maybe we should add tiff and freetype as explicit DEPS in qt6-qtdeclarative.mk to ensure consistency. I don't know if tiff and freetype actually contribute any useful functionality though.

In general, I'm finding it very annoying to deal with cmake and static linking of transitive dependencies. It's probably my lack of knowledge, but I really miss qmake and even pkg-config.

**Comment by mbunkus** [comment]
Yeah, I'm not really amused by that cmake transition either & share your frustration. Anyway.

freetype is already a dependency, albeit an indirect one: `qt6-qtdeclarative` → `qt6-qtbase` → `freetype`. No need to add it to `qt6-qtdeclarative`, or rather, it will always be present during the build of `qt6-qtdeclarative`. Same for `qt6-qttools`.

`tiff` on the other hand is not a dependency at all at the moment. After opening this issue I verified that adding `tiff` to `qt6-qtdeclarative`'s `$(PKG)_DEPS` solves the issue.
