### ISSUE TITLE
Static builds fail for package xmlwrapp on Ubuntu 24.04

### ISSUE THREAD

**Issue by BastyCDGS** [mxe/mxe#3164]
When I try to build xmlwrapp static libraries on Ubuntu 24.04, it fails with a configure error, not finding boost iostreams library. Log file is in gist:
https://gist.github.com/BastyCDGS/870e26b8bbc7bacb66c0f2c78743a418

**Comment by mabrand** [comment]
Hi,
I have closed these issues (#3121-#3164) because I doubt the project can deal with such a number of similar entries at once. My impression is that all, many, or most of them are about 32-bit targets (i686-w64-mingw32.*) and for packages I am not personally well-acquainted with. It's likely that at least some of the issues share underlying problems.

My suggestion would be for you to reopen one or two packages that are of particular interest to you. That should attract more focused participation, increasing the likelihood of a solution. Tested patches in pull requests would be especially welcome of course.

**Comment by BastyCDGS** [comment]
Hi!
Thank you very much for your reply!

Another note, most issues aren't 32-bit specific, but about static / shared build problems, because configure doesn't find the libraries (similar to the libatomic issue in qtbase package which you already fixed).

If an issue was 32-bit only, I mentioned it in the subject and text. I just added the 32-bit log if both failed, because both logs are very similar.

The patches mostly address compilation issues with GCC 11 and later which changed some default parameters, like the -fpermissive vs. -fno-permissive or C++ default standard (no more allowed dynamic exceptions in C++17 and above). Some of them also fix compatibility problems with older library versions.

Should I put the patches as pull requests, almost all of them are very simple, though, adding a missing include for GCC 11 or newer library. I actually tried to make pull requests, but there is something that confused me. It requires me to compare two branches, but since the problem is in the master, it does not make sense...so what I have to do?

Best regards,
Basty
