### ISSUE TITLE
build-requirements builds all requirements even if the correct versions are already installed

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#376]
For example I have automake 1.14 on my system but I have all the other dependencies like m4 and sed with supported versions installed. Now if I run `make build-requirements` it builds all the dependencies.

**Comment by tonytheodore** [comment]
> This is partly intentional at the moment

I'd say it's fully intentional now, even with the right versions, they may fail a [functionality test](https://github.com/mxe/mxe/commit/989f09ca99a56cdb68f5f4b2dc65e9390b29289f).

> It's a "works for me" experiment that I'm not sure will (or can) become a supported part of MXE.

N.B., `build-requirements` is going to be removed shortly - there will be similar functionality with a different invocation.
