### ISSUE TITLE
boost fails to build

### ISSUE THREAD

**Issue by uwehermann** [mxe/mxe#573]
```
Failed to build package boost!
------------------------------------------------------------
/home/uwe/mxe-git-qt5/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_system-mt
/home/uwe/mxe-git-qt5/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_chrono-mt
collect2: error: ld returned 1 exit status
Makefile:438: recipe for target 'build-only-boost_i686-w64-mingw32.static' failed
make[1]: *** [build-only-boost_i686-w64-mingw32.static] Error 1
```

Partial log (full log is too long even for the pastebin):
http://pastebin.com/QEPG6w1W

**Comment by crazybytes** [comment]
Oh hell, just stop it.
Are you all trolls?

Tell them all to fix everything really soon, or they all will be in court very soon, and wil have to pay for all the corrupted open source.

So fix it quick, contact all responsible creators and maintainers of all the open source, and tell them to fix it really fast, because i am almost dead.

you fix the sfemovie / new ffmpeg distro so they match,
you fix the mxe and msys2 shit.
contact the ffmpeg msys2 mxe sfemovie and sfml team, to fix things really fast, all together.
I know they are reading this, and stop trolling  around and corrupting shit and make it public what you did, the illuminati guys are on they way back, but fist they have to fix everything.
Its an ultimatum you know!
so stop talking around like this, and order them all to fix it fast, i know they can.

And if they don't, they will have to pay the price for that
someday somehow, maybe even in hell, were they come from....
