### ISSUE TITLE
libwebsockets does not compile

### ISSUE THREAD

**Issue by newnon** [mxe/mxe#616]
after commit 8dfc4aa with openssl update libwebsockets does not compile any more.

**Comment by TimothyGu** [comment]
@mabrand can you please take a look at it as you updated OpenSSL? Thanks.

**Comment by mabrand** [comment]
I pushed 4259259359f4988efffca207658cad79a25a2653 which fixes finding openssl. I guess libwebsockets was previously using the hosts FindOpenSSL.cmake.

Building libwebsockets now runs into another when it doesn't find vfork. It seems unlikely that this is related to the openssl upgrade at all. How did it ever work? My cmake fu is limited. Do you have any ideas?

**Comment by mabrand** [comment]
Hmm. The FindOpenSSL.cmake file my patch added somehow leads to the vfork problem, also with openssl 1.0.1. Puzzling..

**Comment by mabrand** [comment]
A newer version of FindOpenSSL.cmake and friends seems do the trick. 01af85c10a87abe39d3d84770ea5cc9b80681097
Is there a better way to do this?

**Comment by newnon** [comment]
Sorry cmake is kind of black magic for me.

**Comment by newnon** [comment]
Thanks libwebsockets compile again i think this issues can be closed?

**Comment by TimothyGu** [comment]
@mabrand thanks for fixing this. Don't think there is any more ways of doing it. Is FindOpenSSL.cmake bundled with CMake or OpenSSL? If it is with CMake it might be better if we directly put them in src/cmake, instead of in a patch then install it to src/cmake.

@newnon thanks for reporting this issue. Closed.
