### ISSUE TITLE
Undefined references while linking Qt/CMake project

### ISSUE THREAD

**Issue by martinhanzik** [mxe/mxe#617]
I am starting a project with C++11, CMake, Qt and Boost and when cross compiling on Ubuntu Server 14.10, I get these errors ( http://pastebin.com/T73PdLwY ) when it gets to linking the executable. The same error occurred when building on my main, Mac OS X 10.10.

I have mxe built from the master branch for Qt 5.4.0 and Boost 1.57.0.

The command I use to build is
```
cmake -DCMAKE_TOOLCHAIN_FILE=/opt/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake -DCMAKE_PREFIX_PATH=/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/cmake/ ..
```
All the relevant sources and CMakeLists.txt can be found here https://github.com/EditCraft/EditCraft if needed.

**Comment by martinhanzik** [comment]
When I inspected the command that was run for linking
```
/opt/mxe/usr/bin/i686-w64-mingw32.static-g++  -Wall -pedantic -Wextra -ggdb3 -O3 -DNDEBUG    -Wl,--whole-archive CMakeFiles/editcraft.dir/objects.a -Wl,--no-whole-archive  -o ../bin/editcraft.exe -Wl,--out-implib,libeditcraft.dll.a -Wl,--major-image-version,0,--minor-image-version,0  /opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Core.a /opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Gui.a /opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Widgets.a -Wl,-Bstatic -lboost_iostreams-mt -lnbt++ /opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Gui.a /opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Core.a -Wl,-Bdynamic -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
```
I realized it might be missing some -l parameters, when adding these `-lpcre16 -lpng -lz -ljpeg -lharfbuzz -lopengl32 -lglib-2.0 -lintl -liconv`, the amout of errors decreased, the remaining ones are here: http://pastebin.com/mffEX8hP
Haven't managed to link the rest.

**Comment by TimothyGu** [comment]
Static compilation with CMake and Qt is a long standing issue, and not one with MXE. See some more discussion here: u8sand/Baka-MPlayer#7.

Basically, it all boils down to:

1. Use a better build system like qmake, or
2. Use shared builds.

CMake is broken in this aspect, because it doesn't distinguish between shared *linking*, where you only need to link to the libs you are directly using, versus static linking, where you have to specify every single dependency you use, including the dependencies of the dependency. Technically you can linking to shared libs the static way, but CMake does the opposite: it only stores shared linking information.

autotools and pkg-config handle this through the use of `Require.private` etc. But autotools don't integrate that well with Qt.

qmake does not suffer from this issue, and is the recommended way to build Qt projects, as it is developed by Qt. The project I referenced earlier did switch to qmake and AFAIK there's no issue with it. Plus the build config files are easier to write too IMO.

**Comment by martinhanzik** [comment]
Ok, thanks, I was originally trying to avoid qmake for various reasons, but I'm not too happy with CMake either way, so I'll just have to switch then. Sorry for bothering you with this, since it happened only when cross compiling, I thought it was a MXE issue.

**Comment by mabrand** [comment]
Are you this problem is characterized by *cross-compiling* with cmake? Like TImothyGu, I associate this problem with static linking with cmake, not specifically cross-compiling. Cross-compiling using shared linking with cmake might just work.

I also agree that qmake is the natural choice. Its support for pkg-config might be better than you realize. I've used it very reliably.
http://qt-project.org/faq/answer/does_qmake_have_support_for_pkg-config
