### ISSUE TITLE
warning when compiling test-boost.exe

### ISSUE THREAD

**Issue by abma** [mxe/mxe#666]
i'm getting this warning when trying to recompile boost-test.exe:

duplicate section `.rdata$_ZTSN5boost7archive6detail18interface_oarchiveINS0_12xml_oarchiveEEE[__ZTSN5boost7archive6detail18interface_oarchiveINS0_12xml_oarchiveEEE]' has different size
...

the command i'm using is copied/fixed from src/boost.mk:

usr/bin/i686-w64-mingw32.static-g++ \
        -W -Wall -Werror -ansi -U__STRICT_ANSI__ -pedantic \
        src/boost-test.cpp -o test-boost.exe \
        -DBOOST_THREAD_USE_LIB \
        -lboost_serialization-mt \
        -lboost_thread_win32-mt \
        -lboost_system-mt \
        -lboost_chrono-mt

any idea what i'm doing wrong? whats different when test-boost.exe is compiled with mxe? (which works)

i'm using current mxe (4d98af4ef7d0e4262ff725ad286f93208001149a)

how can i fix this warning?

edit: the warning also happens when mxe compiles it, see log/boost

**Comment by luckyhacky** [comment]
made a test with 745eb5365e16fddf90c4492bea98726838688f71 and compilation is done withoud any errors. Can you retest?

**Comment by tonytheodore** [comment]
`gcc` has since been updated and I can't reproduce this. I suspect it may be about [compiling with different options](http://stackoverflow.com/questions/11635485/regex-boost-library-linking-in-release-mode-warns-duplicate-section-has-differe) but can't get the same error after trying many options (a different one with `-march=i386`). 

Please reopen if it's still happening.
