### ISSUE TITLE
Update FFmpeg to 2.6.3 

### ISSUE THREAD

**Issue by CoolOppo** [mxe/mxe#692]

**Comment by TimothyGu** [comment]
Try

```sh
make update-package-ffmpeg
```

It should work just fine.

If not edit src/ffmpeg.mk by hand to update the VERSION and then run `make update-checksum-ffmpeg`.

**Comment by CoolOppo** [comment]
Oh my bad I actually figured out how that rule works so I ended up doing that myself, which does in fact work just fine!

I ended up just building FFmpeg's HEAD version since they recommend doing that anyways over using releases (which are just exact snapshots of the Git repository at given points in time when it comes to FFmpeg, IIRC).

**Comment by TimothyGu** [comment]
> I ended up just building FFmpeg's HEAD version since they recommend doing that anyways over using releases

FFmpeg guarantees API compat within a release branch and that's why I prefer using a release.

> (which are just exact snapshots of the Git repository at given points in time when it comes to FFmpeg, IIRC)

No. FFmpeg uses a branching scheme similar to that of the kernel. E.g., master branched into release/2.6 → after a few days n2.6 is tagged on release/2.6 branch → bug fixes from master cherry-picked into release/2.6 → n2.6.1 is tagged on that branch.

(As you can see I'm a member of @FFmpeg)

**Comment by CoolOppo** [comment]
Oh, thanks for filling me in. I feel like a total moron now - I can't stand it when people spread misinformation like I pretty much just did.

**Comment by TimothyGu** [comment]
No worries :smile:
