### ISSUE TITLE
Qt deployed to Win XP

### ISSUE THREAD

**Issue by u8sand** [mxe/mxe#700]
This is a known issue that was fixed back in 2013 upstream (https://bugreports.qt.io/browse/QTBUG-29306). But it's still present--can we get a patch for it? It's somewhat an annoying little bug which just kills it for that platform.

I'm in the process of trying to make the patch myself but I can't access that last link and I have no clue where to look to apply the following: https://codereview.chromium.org/download/issue12189010_1_2.diff.

Thank you

**Comment by mabrand** [comment]
I assume you are talking about Qt 5, since that's what QTBUG-29306 mentions. Unfortunately, that QTBUG doesn't seem to link to the relevant change. Maybe it was just a change to the version of MinGW bundled with Qt at that time. You might be able to find the patch in Qt's binary distributions for MinGW.

Note that Qt 5.4 supports WinXP "for deployment only". Building with current tools and libraries is likely to get increasingly difficult.

**Comment by tonytheodore** [comment]
The chromium patch you linked to essentially uses an internal (v8?) implementation. You can (possibly) use that implementation in your project - it's not something we can adopt.
